version: '2'

services: 
  data:
    image: tianon/true
    volumes:
      - ./:/flask

  python:
    build: .
    volumes_from:
      - data
    ports:
      - 5000:5000
    environment:
      - FLASK_APP
