version: '2'

services: 
  data:
    image: tianon/true
    volumes:
      - ./:/flask
      - ./docker/nginx/flask.conf:/etc/nginx/conf.d/flask.conf

  nginx:
    image: nginx:alpine
    depends_on:
      - python
    ports:
      - 8080:8080
    volumes_from:
      - data

  python:
    build: .
    ports:
      - 5000:5000
    volumes_from:
      - data
